common:
  msg_source: 3                                         #0: not use Lidar
                                                        #1: packet message comes from online Lidar
                                                        #2: packet message comes from ROS or ROS2
                                                        #3: packet message comes from Pcap file
  send_packet_ros: false                                #true: Send packets through ROS or ROS2(Used to record packet)
  send_point_cloud_ros: true                            #true: Send point cloud through ROS or ROS2                          
  send_packet_proto: false                              
  send_point_cloud_proto: false
lidar:
  - driver:
      lidar_type: RSHELIOS         #LiDAR type - RS16, RS32, RSBP, RSHELIOS, RSHELIOS_16P, RS128, RS80, RS48, RSP128, RSP80, RSP48, 
                                   #             RSM1, RSM1_JUMBO, RSM2, RSE1
      msop_port: 6705              #Msop port of lidar
      difop_port: 7794             #Difop port of lidar
      start_angle: 0               #Start angle of point cloud
      end_angle: 360               #End angle of point cloud 
      wait_for_difop: true
      min_distance: 0.2            #Minimum distance of point cloud
      max_distance: 200            #Maximum distance of point cloud
      use_lidar_clock: false       #True--Use the lidar clock as the message timestamp
                                   #False-- Use the system clock as the timestamp
      pcap_path: path_to_pcap.pcap #The path of pcap file
    ros:
      ros_frame_id: rsHELIOS_SB                           #Frame id of packet message and point cloud message
      ros_recv_packet_topic: /rsHELIOS_SB_packets          #Topic used to receive lidar packets from ROS
      ros_send_packet_topic: /rsHELIOS_SB_packets          #Topic used to send lidar packets through ROS
      ros_send_point_cloud_topic: /rsHELIOS_SB_points      #Topic used to send point cloud through ROS

  - driver:
      lidar_type: RSHELIOS         #LiDAR type - RS16, RS32, RSBP, RSHELIOS, RSHELIOS_16P, RS128, RS80, RS48, RSP128, RSP80, RSP48, 
                                   #             RSM1, RSM1_JUMBO, RSM2, RSE1
      msop_port: 6706              #Msop port of lidar
      difop_port: 7795             #Difop port of lidar
      start_angle: 0               #Start angle of point cloud
      end_angle: 360               #End angle of point cloud 
      wait_for_difop: true
      min_distance: 0.2            #Minimum distance of point cloud
      max_distance: 200            #Maximum distance of point cloud
      use_lidar_clock: false       #True--Use the lidar clock as the message timestamp
                                   #False-- Use the system clock as the timestamp
      pcap_path: path_to_pcap.pcap #The path of pcap file
    ros:
      ros_frame_id: rsHELIOS_PT                           #Frame id of packet message and point cloud message
      ros_recv_packet_topic: /rsHELIOS_PT_packets          #Topic used to receive lidar packets from ROS
      ros_send_packet_topic: /rsHELIOS_PT_packets          #Topic used to send lidar packets through ROS
      ros_send_point_cloud_topic: /rsHELIOS_PT_points      #Topic used to send point cloud through ROS

  - driver:
      lidar_type: RSE1         #LiDAR type - RS16, RS32, RSBP, RSHELIOS, RSHELIOS_16P, RS128, RS80, RS48, RSP128, RSP80, RSP48, 
                                   #             RSM1, RSM1_JUMBO, RSM2, RSE1
      msop_port: 31003              #Msop port of lidar
      difop_port: 31004             #Difop port of lidar
      group_address: 224.0.0.205    # Group address
      host_address: 198.18.35.2     # Host address

      start_angle: 0               #Start angle of point cloud
      end_angle: 360               #End angle of point cloud 
      wait_for_difop: true
      min_distance: 0.2            #Minimum distance of point cloud
      max_distance: 200            #Maximum distance of point cloud
      use_lidar_clock: false       #True--Use the lidar clock as the message timestamp
                                   #False-- Use the system clock as the timestamp
      pcap_path: path_to_pcap.pcap #The path of pcap file
    ros:
      ros_frame_id: RSE1_stern                           #Frame id of packet message and point cloud message
      ros_recv_packet_topic: /RSE1_stern_packets          #Topic used to receive lidar packets from ROS
      ros_send_packet_topic: /RSE1_stern_packets          #Topic used to send lidar packets through ROS
      ros_send_point_cloud_topic: /RSE1_stern_points      #Topic used to send point cloud through ROS